language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

install:
  - go get -d -t github.com/keinohguchi/go-amqp-opentracing/...
  - go get -u github.com/golang/lint/...
script:
  - make test lint
  - go build ./...
